sudo: false
language: go
# handle submodules ourselves
git:
  submodules: false
env:
  - PROTOBUF_VERSION=2.6.1
go:
  - 1.7.x
  - 1.8
before_install:
   #these two lines help users who fork mesos-go. It's a noop when running from the mesos organization
  - RepoName=`basename $PWD`; SrcDir=`dirname $PWD`; DestDir="`dirname $SrcDir`/mesos"
  - if [[ "$SrcDir" != "$DestDir" ]]; then mv "$SrcDir" "$DestDir"; cd ../../mesos/$RepoName; export TRAVIS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/$RepoName; fi
  - go get github.com/mattn/goveralls
  - go get github.com/kardianos/govendor
  - make sync
  - api/v1/vendor/github.com/gogo/protobuf/install-protobuf.sh
  # re-generate protobuf and json code, check that there are no differences w/ respect to what's been checked in
  - (cd api/v1; govendor install +vendor,program) && make protobufs ffjson && [[ `{ git status --porcelain || echo "failed"; } | wc -l` = "0" ]]
install:
  - make test install
script:
  - if [[ "$TRAVIS_EVENT_TYPE" = "pull_request" ]] || [[ "$TRAVIS_BRANCH" = "master" ]]; then make coveralls; fi
